language: node_js
node_js:
  - "6"
  - "5"
  - "4"

branches:
  only:
    - master

install:
  - npm install
before_script:
   - ./build/start-server.sh
script: make
after_script:
   - ./build/stop-server.sh